language: rust
matrix:
  include:
    # litmus check that we work on stable/beta
    - rust: stable
      env: FEATURES='default' MODE='test'
    - rust: beta
      env: FEATURES='default' MODE='test'
    # actually test everything
    - rust: nightly
      env: FEATURES='default' MODE='test'
    - rust: nightly
      env: FEATURES='std' MODE='test'
    - rust: nightly
      env: FEATURES='alloc' MODE='build'
    - rust: nightly
      env: FEATURES='phy-raw_socket' MODE='build'
    - rust: nightly
      env: FEATURES='phy-tap_interface' MODE='build'
    - rust: nightly
      env: FEATURES='' MODE='build'
script:
   - cargo "$MODE" --no-default-features --features "$FEATURES"
notifications:
  irc:
    channels:
      - "chat.freenode.net#m-labs"
    use_notice: true
    skip_join: true
