language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable # until 1.15 comes out
notifications:
  irc:
    channels:
      - "chat.freenode.net#m-labs"
    use_notice: true
    skip_join: true
