language: rust
matrix:
  include:
    # litmus check that we work on stable/beta
    - rust: stable
      env: FEATURES='default' MODE='test'
    - rust: beta
      env: FEATURES='default' MODE='test'
    # actually test everything
    - rust: nightly
      env: FEATURES='default' MODE='test'
    - rust: nightly
      env: FEATURES='phy-raw_socket proto-udp' MODE='build'
    - rust: nightly
      env: FEATURES='phy-tap_interface proto-udp' MODE='build'
    - rust: nightly
      env: FEATURES='proto-raw' MODE='build'
    - rust: nightly
      env: FEATURES='proto-udp' MODE='build'
    - rust: nightly
      env: FEATURES='proto-tcp' MODE='build'
    - rust: nightly
      env: FEATURES='proto-raw proto-udp proto-tcp' MODE='build'
    - rust: nightly
      env: FEATURES='proto-raw proto-udp proto-tcp std' MODE='build'
    - rust: nightly
      env: FEATURES='proto-raw proto-udp proto-tcp alloc' MODE='build'
script:
   - cargo "$MODE" --no-default-features --features "$FEATURES"
notifications:
  irc:
    channels:
      - "chat.freenode.net#m-labs"
    use_notice: true
    skip_join: true
