language: rust
matrix:
  include:
    # litmus check that we work on stable/beta
    - rust: stable
      env: FEATURES='default' MODE='test'
    - rust: beta
      env: FEATURES='default' MODE='test'
    # actually test everything
    - rust: nightly
      env: FEATURES='default' MODE='test'
    - rust: nightly
      env: FEATURES='phy-raw_socket' MODE='build'
    - rust: nightly
      env: FEATURES='phy-tap_interface' MODE='build'
    - rust: nightly
      env: FEATURES='socket-raw' MODE='build'
    - rust: nightly
      env: FEATURES='socket-udp' MODE='build'
    - rust: nightly
      env: FEATURES='socket-tcp' MODE='build'
    - rust: nightly
      env: FEATURES='socket-raw socket-udp socket-tcp' MODE='build'
    - rust: nightly
      env: FEATURES='socket-raw socket-udp socket-tcp std' MODE='build'
    - rust: nightly
      env: FEATURES='socket-raw socket-udp socket-tcp alloc' MODE='build'
script:
   - cargo "$MODE" --no-default-features --features "$FEATURES"
notifications:
  irc:
    channels:
      - "chat.freenode.net#m-labs"
    use_notice: true
    skip_join: true
