[package]
name = "smoltcp"
version = "0.1.0"
authors = ["whitequark <whitequark@whitequark.org>"]
license = "0BSD"
license-file = "LICENSE-0BSD"

[dependencies]
byteorder = { version = "0.5", default-features = false }
libc = { version = "0.2.18", optional = true }

[features]
std = ["libc"]
default = ["std"]
