[package]
name = "smoltcp"
version = "0.1.0"
authors = ["whitequark <whitequark@whitequark.org>"]
license = "0BSD"

[dependencies]
byteorder = { version = "0.5", default-features = false }
log = { version = "0.3", optional = true }
libc = { version = "0.2.18", optional = true }

[dev-dependencies]
env_logger = "0.3"

[features]
use_std = ["libc"]
use_log = ["log"]
default = ["use_std", "use_log"]
