[package]
name = "smoltcp"
version = "0.4.0"
authors = ["whitequark <whitequark@whitequark.org>"]
description = "A TCP/IP stack designed for bare-metal, real-time systems without a heap."
documentation = "https://docs.rs/smoltcp/"
homepage = "https://github.com/m-labs/smoltcp"
repository = "https://github.com/m-labs/smoltcp.git"
readme = "README.md"
keywords = ["ip", "tcp", "udp", "ethernet", "network"]
categories = ["embedded"]
license = "0BSD"

[dependencies]
byteorder = { version = "1.0", default-features = false }
log = { version = "0.3", default-features = false, optional = true }
libc = { version = "0.2.18", optional = true }

[dependencies.managed]
git = "https://github.com/m-labs/rust-managed.git"
rev = "629a6786a1cf1692015f464ed16c04eafa5cb8d1"
default-features = false
features = ["map"]

[dev-dependencies]
env_logger = "0.4"
getopts = "0.2"
rand = "0.3"
url = "1.0"

[features]
std = ["managed/std"]
alloc = ["managed/alloc"]
verbose = []
"phy-raw_socket" = ["std", "libc"]
"phy-tap_interface" = ["std", "libc"]
"proto-ipv6" = []
"socket-raw" = []
"socket-udp" = []
"socket-tcp" = []
"socket-icmp" = []
default = [
  "std", "log", # needed for `cargo test --no-default-features --features default` :/
  "phy-raw_socket", "phy-tap_interface",
  "socket-raw", "socket-icmp", "socket-udp", "socket-tcp"
]

[[example]]
name = "tcpdump"
required-features = ["std", "phy-raw_socket"]

[[example]]
name = "httpclient"
required-features = ["std", "phy-tap_interface", "socket-tcp"]

[[example]]
name = "ping"
required-features = ["std", "phy-tap_interface", "socket-icmp"]

[[example]]
name = "server"
required-features = ["std", "phy-tap_interface", "socket-tcp", "socket-udp"]

[[example]]
name = "client"
required-features = ["std", "phy-tap_interface", "socket-tcp", "socket-udp"]

[[example]]
name = "loopback"
required-features = ["alloc", "proto-ipv4"]

# This is really a test, but it requires root privileges for setup (the tap interface)
# so it is built as an example.
[[example]]
name = "stress"
required-features = ["std", "phy-tap_interface", "socket-tcp"]
